// <auto-generated />
using System;
using HRIS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRIS.Infrastructure.Migrations
{
    [DbContext(typeof(HRISDbContext))]
    [Migration("20251127061048_AddedMarkUpdatedAndFixedEmployeeEntityAttributes")]
    partial class AddedMarkUpdatedAndFixedEmployeeEntityAttributes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.HRIS.Employee", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CivilStatusID")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EmploymentID")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ExtensionName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDualCitizen")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFilipino")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SexAtBirth")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeID");

                    b.HasIndex("CivilStatusID");

                    b.HasIndex("EmploymentID")
                        .IsUnique();

                    b.ToTable("Employees", "hris");
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.HRIS.EmployeeIdentification", b =>
                {
                    b.Property<Guid>("EmployeeIdentificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiredDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdentificationTypeID")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssuedPlace")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("EmployeeIdentificationID");

                    b.HasIndex("IdentificationTypeID");

                    b.HasIndex("EmployeeID", "IdentificationTypeID")
                        .IsUnique();

                    b.ToTable("EmployeeIdentifications", "hris");
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.Lookup.CivilStatus", b =>
                {
                    b.Property<int>("CivilStatusID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CivilStatusID"));

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StatusDescription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CivilStatusID");

                    b.ToTable("CivilStatuses", "lookup");

                    b.HasData(
                        new
                        {
                            CivilStatusID = 1,
                            StatusCode = "S",
                            StatusDescription = "Single"
                        },
                        new
                        {
                            CivilStatusID = 2,
                            StatusCode = "M",
                            StatusDescription = "Married"
                        },
                        new
                        {
                            CivilStatusID = 3,
                            StatusCode = "W",
                            StatusDescription = "Widowed"
                        },
                        new
                        {
                            CivilStatusID = 4,
                            StatusCode = "S",
                            StatusDescription = "Separated"
                        });
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.Lookup.IdentificationType", b =>
                {
                    b.Property<int>("IdentificationTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdentificationTypeID"));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("IdentificationTypeID");

                    b.ToTable("IdentificationTypes", "lookup");

                    b.HasData(
                        new
                        {
                            IdentificationTypeID = 1,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Tax Identification Number",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "TIN"
                        },
                        new
                        {
                            IdentificationTypeID = 2,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "PhilHealth ID",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "PhilHealth"
                        },
                        new
                        {
                            IdentificationTypeID = 3,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Social Security System ID",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "SSS"
                        },
                        new
                        {
                            IdentificationTypeID = 4,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Government Service Insurance System ID",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "GSIS"
                        },
                        new
                        {
                            IdentificationTypeID = 5,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Philippine National ID",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "National ID"
                        },
                        new
                        {
                            IdentificationTypeID = 6,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "PRC License",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "PRC License"
                        },
                        new
                        {
                            IdentificationTypeID = 7,
                            CreatedBy = "",
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Driver's License ID",
                            Id = new Guid("00000000-0000-0000-0000-000000000000"),
                            IsActive = true,
                            Type = "Driver's License"
                        });
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.HRIS.Employee", b =>
                {
                    b.HasOne("HRIS.Domain.Entities.Domain.Lookup.CivilStatus", "CivilStatus")
                        .WithMany("Employees")
                        .HasForeignKey("CivilStatusID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CivilStatus");
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.HRIS.EmployeeIdentification", b =>
                {
                    b.HasOne("HRIS.Domain.Entities.Domain.HRIS.Employee", "Employee")
                        .WithMany("EmployeeIdentifications")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRIS.Domain.Entities.Domain.Lookup.IdentificationType", "IdentificationType")
                        .WithMany("EmployeeIdentifications")
                        .HasForeignKey("IdentificationTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("IdentificationType");
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.HRIS.Employee", b =>
                {
                    b.Navigation("EmployeeIdentifications");
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.Lookup.CivilStatus", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRIS.Domain.Entities.Domain.Lookup.IdentificationType", b =>
                {
                    b.Navigation("EmployeeIdentifications");
                });
#pragma warning restore 612, 618
        }
    }
}
